# Generated by Django 4.2.7 on 2023-12-15 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 15, 11, 11, 22, 979988)),
        ),
    ]
